In [319]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import classification_report

In [320]:
df=pd.read_csv('sonar data.csv',header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [321]:
df.shape

(208, 61)

In [322]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [323]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [324]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [325]:
X=df.drop(60,axis='columns')
y=df[60]

In [326]:
X

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [327]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [328]:
y=pd.get_dummies(y,drop_first=True)
y.sample(5)

R
121  0
67   1
93   1
152  0
8    1

In [329]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [330]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=2)

In [331]:
X_train.shape,X_test.shape

((156, 60), (52, 60))

In [332]:
model=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy']
             )

model.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6942 - accuracy: 0.5192
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6722 - accuracy: 0.5962
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6548 - accuracy: 0.6090
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6334 - accuracy: 0.7179
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5943 - accuracy: 0.6923
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5692 - accuracy: 0.7564
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5224 - accuracy: 0.7500
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4858 - accuracy: 0.7756
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4486 - accuracy: 0.8077
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.8141
Epoch 11/

In [333]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 12ms/step - loss: 0.6002 - accuracy: 0.8269


[0.6001816391944885, 0.8269230723381042]

In [334]:
y_pred=model.predict(X_test)
y_pred[:10]

2/2 [==============================] - 0s 5ms/step


array([[3.8448621e-02],
       [5.6567533e-05],
       [7.6314180e-05],
       [9.9994707e-01],
       [9.7623509e-01],
       [9.6819735e-01],
       [2.3228185e-04],
       [9.9999321e-01],
       [9.9985683e-01],
       [1.2795921e-02]], dtype=float32)

In [335]:
y_pred=np.round(y_pred)
y_pred[:10]

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [336]:
y_test[:10]

R
154  0
192  0
135  0
10   1
13   1
173  0
205  0
23   1
71   1
28   1

In [337]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       0.96      0.76      0.85        34
         1.0       0.68      0.94      0.79        18

    accuracy                           0.83        52
   macro avg       0.82      0.85      0.82        52
weighted avg       0.87      0.83      0.83        52



In [338]:
model2=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation='sigmoid')
])

model2.compile(loss='binary_crossentropy',
               optimizer='adam',
               metrics=['accuracy']
              )

model2.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 3ms/step - loss: 0.7328 - accuracy: 0.5064
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6976 - accuracy: 0.5449
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7001 - accuracy: 0.5000
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7112 - accuracy: 0.5000
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6937 - accuracy: 0.5064
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6891 - accuracy: 0.5321
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6961 - accuracy: 0.4551
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6959 - accuracy: 0.5256
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6990 - accuracy: 0.5385
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6912 - accuracy: 0.5513
Epoch 11/

In [339]:
model2.evaluate(X_test,y_test)

2/2 [==============================] - 0s 11ms/step - loss: 0.3905 - accuracy: 0.8462


[0.39053356647491455, 0.8461538553237915]

In [340]:
y_pred2=model2.predict(X_test)
y_pred2[:10]

2/2 [==============================] - 0s 6ms/step


array([[0.22945069],
       [0.0484176 ],
       [0.12421456],
       [0.9995339 ],
       [0.9818488 ],
       [0.1641239 ],
       [0.08651106],
       [0.99740815],
       [0.98719263],
       [0.17757358]], dtype=float32)

In [341]:
y_pred2=np.round(y_pred)
y_pred2[:10]

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [342]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

         0.0       0.96      0.76      0.85        34
         1.0       0.68      0.94      0.79        18

    accuracy                           0.83        52
   macro avg       0.82      0.85      0.82        52
weighted avg       0.87      0.83      0.83        52

